# Generated by Django 3.2.8 on 2021-10-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loggin',
        ),
    ]
